base_url = "/"
title = "Robert Yin"
description = "Robert Yin's Site"
default_language = "en"

compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[extra]
version = "1.7.0"
