base_url = "/"
title = "Robert Yin"
description = "Robert Yin's Site"
default_language = "en"

compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"
external_links_target_blank = true
smart_punctuation = true

[extra]
profile = "robert.jpeg"
version = "2.6.0"
email = "bobertoyin@gmail.com"
github = "bobertoyin"
linkedin = "boberto"
location = "Boston, MA"
resume = "resume.pdf"
[extra.job]
title = "Incoming Software Developer"
company = "Epic"
link = "https://epic.com"
[extra.education]
degree = "BSCS Candidate"
school = "NEU"
link = "https://northeastern.edu"
